export const CHANGE_TO_HOME = 'CHANGE_TO_HOME'
export type CHANGE_TO_HOME = typeof CHANGE_TO_HOME

export const CHANGE_TO_GAME = 'CHANGE_TO_GAME'
export type CHANGE_TO_GAME = typeof CHANGE_TO_GAME

export const CHANGE_TO_NORMAL = 'CHANGE_TO_NORMAL'
export type CHANGE_TO_NORMAL = typeof CHANGE_TO_NORMAL

export const CHANGE_TO_ABOUT = 'CHANGE_TO_ABOUT'
export type CHANGE_TO_ABOUT = typeof CHANGE_TO_ABOUT

export const CHANGE_TO_PORTFOLIO = 'CHANGE_TO_PORTFOLIO'
export type CHANGE_TO_PORTFOLIO = typeof CHANGE_TO_PORTFOLIO

export const CHANGE_TO_CONTACT = 'CHANGE_TO_CONTACT'
export type CHANGE_TO_CONTACT = typeof CHANGE_TO_CONTACT

export const TOGGLE_TYPE = 'TOGGLE_TYPE'
export type TOGGLE_TYPE = typeof TOGGLE_TYPE

export const SET_LARGE_SCREEN = 'SET_LARGE_SCREEN'
export type SET_LARGE_SCREEN = typeof SET_LARGE_SCREEN

export const SET_SMALL_SCREEN = 'SET_SMALL_SCREEN'
export type SET_SMALL_SCREEN = typeof SET_SMALL_SCREEN
